GAME_INFO_FIXTURE = """<?xml version="1.0" ?>

<Replay>

    <ClientVersion>3.0.219.2</ClientVersion>

    <ReplayStep>
        <GameInfos>
            <AnswerClock>-1</AnswerClock>
            <TurnClockDuration>180000</TurnClockDuration>
            <CoachesInfos>
                <CoachInfos>
                    <Login>AI</Login>
                    <UserId>AI</UserId>
                </CoachInfos>
                <CoachInfos>
                    <Slot>1</Slot>
                    <Login>JudgeGregg</Login>
                    <UserId>JudgeGregg</UserId>
                </CoachInfos>
            </CoachesInfos>
        </GameInfos>
        <BoardState>
            <ListTeams>
                <TeamState>
                    <Data>
                        <Name>Team1</Name>
                    </Data>
                </TeamState>
                <TeamState>
                    <Data>
                        <Name>Team2</Name>
                    </Data>
                </TeamState>
            </ListTeams>
        </BoardState>
    </ReplayStep>
</Replay>
"""

WEATHER_FANS_FIXTURE = """<?xml version="1.0" ?>
<Replay>
<ReplayStep>
    <RulesEventKickOffChoice>
            <ChosingTeam>1</ChosingTeam>
    </RulesEventKickOffChoice>
    <RulesEventBoardAction>
            <RequestType>1</RequestType>
            <ActionType>46</ActionType>
            <Order>
                    <CellTo/>
                    <CellFrom/>
            </Order>
            <Results>
                    <BoardActionResult>
                            <ListModifiers/>
                            <IsOrderCompleted>1</IsOrderCompleted>
                            <RollType>69</RollType>
                            <CoachChoices>
                                    <ListCells/>
                                    <ListDices>(4,3)</ListDices>
                                    <ListSkills/>
                            </CoachChoices>
                    </BoardActionResult>
                    <BoardActionResult>
                            <ListModifiers/>
                            <IsOrderCompleted>1</IsOrderCompleted>
                            <RollType>69</RollType>
                            <CoachChoices>
                                    <ConcernedTeam>1</ConcernedTeam>
                                    <ListCells/>
                                    <ListDices>(1,6)</ListDices>
                                    <ListSkills/>
                            </CoachChoices>
                    </BoardActionResult>
            </Results>
    </RulesEventBoardAction>
    <RulesEventBoardAction>
            <RequestType>1</RequestType>
            <ActionType>47</ActionType>
            <Order>
                    <CellTo/>
                    <CellFrom/>
            </Order>
            <Results>
                    <BoardActionResult>
                            <ListModifiers/>
                            <IsOrderCompleted>1</IsOrderCompleted>
                            <RollType>70</RollType>
                            <CoachChoices>
                                    <ListCells/>
                                    <ListDices>(4,1)</ListDices>
                                    <ListSkills/>
                            </CoachChoices>
                    </BoardActionResult>
            </Results>
    </RulesEventBoardAction>
</ReplayStep>
</Replay>
"""

DODGE_SUCCESS_FIXTURE = """<?xml version="1.0" ?>
<Replay>
    <ReplayStep>
                <RulesEventBoardAction>
                        <PlayerId>1</PlayerId>
                        <RequestType>1</RequestType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <y>12</y>
                                                <x>9</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>12</y>
                                        <x>10</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <Requirement>4</Requirement>
                                        <ListModifiers>
                                                <DiceModifier>
                                                        <Cell/>
                                                        <Skill>-1</Skill>
                                                        <Type>2</Type>
                                                        <Value>1</Value>
                                                </DiceModifier>
                                        </ListModifiers>
                                        <IsOrderCompleted>1</IsOrderCompleted>
                                        <RollType>2</RollType>
                                        <CoachChoices>
                                                <ListCells/>
                                                <ListDices>(5)</ListDices>
                                                <ListSkills/>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
                <BoardState>
                        <ListTeams>
                                <TeamState>
                                        <GameTurn>1</GameTurn>
                                        <ListPitchPlayers>
                                                <PlayerState>
                                                    <Id>1</Id>
                                                    <Data>
                                                       <Name>Test Player</Name>
                                                       <Id>1</Id>
                                                    </Data>
                                                </PlayerState>
                                        </ListPitchPlayers>
                                </TeamState>
                        </ListTeams>
                </BoardState>
    </ReplayStep>
</Replay>
"""


BLOCK_FIXTURE_WITH_RR = """<?xml version="1.0" ?>
<Replay>
    <ReplayStep>
                <RulesEventBoardAction>
                        <PlayerId>1</PlayerId>
                        <RequestType>1</RequestType>
                        <ActionType>2</ActionType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <y>7</y>
                                                <x>13</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>7</y>
                                        <x>12</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <Requirement>1</Requirement>
                                        <RequestType>5</RequestType>
                                        <ListModifiers>
                                                <DiceModifier>
                                                        <Cell>
                                                                <y>6</y>
                                                                <x>11</x>
                                                        </Cell>
                                                        <Skill>-1</Skill>
                                                        <Type>13</Type>
                                                </DiceModifier>
                                        </ListModifiers>
                                        <ResultType>2</ResultType>
                                        <RollType>5</RollType>
                                        <CoachChoices>
                                                <ListCells/>
                                                <ListDices>(0,0,0,0)</ListDices>
                                                <Reroll>1</Reroll>
                                                <ListSkills/>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
                <RulesEventBoardAction>
                        <PlayerId>1</PlayerId>
                        <RequestType>1</RequestType>
                        <ActionType>2</ActionType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <y>7</y>
                                                <x>13</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>7</y>
                                        <x>12</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <Requirement>1</Requirement>
                                        <RollStatus>1</RollStatus>
                                        <RequestType>2</RequestType>
                                        <ListModifiers>
                                                <DiceModifier>
                                                        <Cell>
                                                                <y>6</y>
                                                                <x>11</x>
                                                        </Cell>
                                                        <Skill>-1</Skill>
                                                        <Type>13</Type>
                                                </DiceModifier>
                                        </ListModifiers>
                                        <ResultType>2</ResultType>
                                        <RollType>5</RollType>
                                        <CoachChoices>
                                                <ListCells/>
                                                <ListDices>(0,2,0,4)</ListDices>
                                                <ListSkills/>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
                <RulesEventBoardAction>
                        <PlayerId>1</PlayerId>
                        <RequestType>1</RequestType>
                        <ActionType>2</ActionType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <y>7</y>
                                                <x>13</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>7</y>
                                        <x>12</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <Requirement>1</Requirement>
                                        <RollStatus>1</RollStatus>
                                        <ListModifiers>
                                                <DiceModifier>
                                                        <Cell>
                                                                <y>6</y>
                                                                <x>11</x>
                                                        </Cell>
                                                        <Skill>-1</Skill>
                                                        <Type>13</Type>
                                                </DiceModifier>
                                        </ListModifiers>
                                        <IsOrderCompleted>1</IsOrderCompleted>
                                        <RollType>5</RollType>
                                        <CoachChoices>
                                                <ListCells/>
                                                <ListDices>(2,4)</ListDices>
                                                <ListSkills/>
                                        </CoachChoices>
                                </BoardActionResult>
                                <BoardActionResult>
                                        <RequestType>3</RequestType>
                                        <ListModifiers/>
                                        <ResultType>2</ResultType>
                                        <RollType>13</RollType>
                                        <CoachChoices>
                                                <ListCells>
                                                        <Cell>
                                                                <y>7</y>
                                                                <x>14</x>
                                                        </Cell>
                                                        <Cell>
                                                                <y>6</y>
                                                                <x>14</x>
                                                        </Cell>
                                                        <Cell>
                                                                <y>8</y>
                                                                <x>14</x>
                                                        </Cell>
                                                </ListCells>
                                                <ListSkills/>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
    </ReplayStep>
</Replay>
"""

BLOCK_FIXTURE_NO_RR = """<?xml version="1.0" ?>
<Replay>
    <ReplayStep>
                <RulesEventBoardAction>
                        <PlayerId>47</PlayerId>
                        <RequestType>1</RequestType>
                        <ActionType>1</ActionType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <y>10</y>
                                                <x>12</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>9</y>
                                        <x>13</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <Requirement>1</Requirement>
                                        <RequestType>2</RequestType>
                                        <ListModifiers>
                                                <DiceModifier>
                                                        <Cell>
                                                                <y>9</y>
                                                                <x>12</x>
                                                        </Cell>
                                                        <Skill>-1</Skill>
                                                        <Type>11</Type>
                                                        <Value>1</Value>
                                                </DiceModifier>
                                        </ListModifiers>
                                        <ResultType>2</ResultType>
                                        <RollType>5</RollType>
                                        <CoachChoices>
                                                <ConcernedTeam>1</ConcernedTeam>
                                                <ListCells/>
                                                <ListDices>(1,2,0,4)</ListDices>
                                                <ListSkills/>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
                <RulesEventBoardAction>
                        <PlayerId>47</PlayerId>
                        <RequestType>1</RequestType>
                        <ActionType>1</ActionType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <y>10</y>
                                                <x>12</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>9</y>
                                        <x>13</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <Requirement>1</Requirement>
                                        <ListModifiers>
                                                <DiceModifier>
                                                        <Cell>
                                                                <y>9</y>
                                                                <x>12</x>
                                                        </Cell>
                                                        <Skill>-1</Skill>
                                                        <Type>11</Type>
                                                        <Value>1</Value>
                                                </DiceModifier>
                                        </ListModifiers>
                                        <IsOrderCompleted>1</IsOrderCompleted>
                                        <RollType>5</RollType>
                                        <CoachChoices>
                                                <ListCells/>
                                                <ListDices>(2,4)</ListDices>
                                                <ListSkills/>
                                        </CoachChoices>
                                </BoardActionResult>
                                <BoardActionResult>
                                        <RequestType>3</RequestType>
                                        <ListModifiers/>
                                        <ResultType>2</ResultType>
                                        <RollType>13</RollType>
                                        <CoachChoices>
                                                <ConcernedTeam>1</ConcernedTeam>
                                                <ListCells>
                                                        <Cell>
                                                                <y>11</y>
                                                                <x>11</x>
                                                        </Cell>
                                                        <Cell>
                                                                <y>11</y>
                                                                <x>12</x>
                                                        </Cell>
                                                        <Cell>
                                                                <y>10</y>
                                                                <x>11</x>
                                                        </Cell>
                                                </ListCells>
                                                <ListSkills/>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
    </ReplayStep>
</Replay>
"""

BLOCK_FIXTURE_RR_LONER = """<?xml version="1.0" ?>
<Replay>
    <ReplayStep>
                <RulesEventBoardAction>
                        <PlayerId>47</PlayerId>
                        <RequestType>1</RequestType>
                        <ActionType>2</ActionType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <y>12</y>
                                                <x>20</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>11</y>
                                        <x>20</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <RequestType>5</RequestType>
                                        <ListModifiers/>
                                        <ResultType>2</ResultType>
                                        <RollType>5</RollType>
                                        <CoachChoices>
                                                <ConcernedTeam>1</ConcernedTeam>
                                                <ListCells/>
                                                <ListDices>(1,0)</ListDices>
                                                <Reroll>1</Reroll>
                                                <ListSkills/>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
                <RulesEventBoardAction>
                        <PlayerId>47</PlayerId>
                        <RequestType>1</RequestType>
                        <ActionType>2</ActionType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <y>12</y>
                                                <x>20</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>11</y>
                                        <x>20</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <Requirement>4</Requirement>
                                        <ListModifiers/>
                                        <ResultType>1</ResultType>
                                        <IsOrderCompleted>1</IsOrderCompleted>
                                        <RollType>23</RollType>
                                        <CoachChoices>
                                                <ConcernedTeam>1</ConcernedTeam>
                                                <ListCells/>
                                                <ListDices>(2)</ListDices>
                                                <ListSkills>
                                                        <SkillInfo>
                                                                <PlayerId>47</PlayerId>
                                                                <SkillId>44</SkillId>
                                                        </SkillInfo>
                                                </ListSkills>
                                        </CoachChoices>
                                </BoardActionResult>
                                <BoardActionResult>
                                        <RollStatus>2</RollStatus>
                                        <RequestType>2</RequestType>
                                        <ListModifiers/>
                                        <ResultType>2</ResultType>
                                        <RollType>5</RollType>
                                        <CoachChoices>
                                                <ConcernedTeam>1</ConcernedTeam>
                                                <ListCells/>
                                                <ListDices>(1,0)</ListDices>
                                                <ListSkills/>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
                <RulesEventBoardAction>
                        <PlayerId>47</PlayerId>
                        <RequestType>1</RequestType>
                        <ActionType>2</ActionType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <y>12</y>
                                                <x>20</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>11</y>
                                        <x>20</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <RollStatus>2</RollStatus>
                                        <ListModifiers/>
                                        <ResultType>3</ResultType>
                                        <IsOrderCompleted>1</IsOrderCompleted>
                                        <RollType>5</RollType>
                                        <CoachChoices>
                                                <ListCells/>
                                                <ListDices>(1,0)</ListDices>
                                                <ListSkills>
                                                        <SkillInfo>
                                                                <PlayerId>4</PlayerId>
                                                                <SkillId>30</SkillId>
                                                        </SkillInfo>
                                                </ListSkills>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
    </ReplayStep>
</Replay>
"""

DODGE_FAILURE_PRE_RR_FIXTURE = """<?xml version="1.0" ?>
<Replay>
    <ReplayStep>
                <RulesEventBoardAction>
                        <PlayerId>46</PlayerId>
                        <RequestType>1</RequestType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <x>17</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>1</y>
                                        <x>17</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <Requirement>4</Requirement>
                                        <RequestType>1</RequestType>
                                        <ListModifiers>
                                                <DiceModifier>
                                                        <Cell/>
                                                        <Skill>-1</Skill>
                                                        <Type>2</Type>
                                                        <Value>1</Value>
                                                </DiceModifier>
                                        </ListModifiers>
                                        <ResultType>2</ResultType>
                                        <RollType>2</RollType>
                                        <CoachChoices>
                                                <ConcernedTeam>1</ConcernedTeam>
                                                <ListCells/>
                                                <ListDices>(1)</ListDices>
                                                <Reroll>1</Reroll>
                                                <ListSkills/>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
    </ReplayStep>
</Replay>
"""

DODGE_FAILURE_POST_RR_FIXTURE = """<?xml version="1.0" ?>
<Replay>
    <ReplayStep>
                <RulesEventBoardAction>
                        <PlayerId>46</PlayerId>
                        <RequestType>1</RequestType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <x>17</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>1</y>
                                        <x>17</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <Requirement>4</Requirement>
                                        <RollStatus>1</RollStatus>
                                        <ListModifiers>
                                                <DiceModifier>
                                                        <Cell/>
                                                        <Skill>-1</Skill>
                                                        <Type>2</Type>
                                                        <Value>1</Value>
                                                </DiceModifier>
                                        </ListModifiers>
                                        <ResultType>3</ResultType>
                                        <IsOrderCompleted>1</IsOrderCompleted>
                                        <RollType>2</RollType>
                                        <CoachChoices>
                                                <ConcernedTeam>1</ConcernedTeam>
                                                <ListCells/>
                                                <ListDices>(2)</ListDices>
                                                <ListSkills/>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
    </ReplayStep>
</Replay>
"""

DODGE_FAILURE_NO_RR_FIXTURE = """<?xml version="1.0" ?>
<Replay>
    <ReplayStep>
                <RulesEventBoardAction>
                        <PlayerId>47</PlayerId>
                        <RequestType>1</RequestType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <y>12</y>
                                                <x>14</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>11</y>
                                        <x>13</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <Requirement>3</Requirement>
                                        <RequestType>1</RequestType>
                                        <ListModifiers>
                                                <DiceModifier>
                                                        <Cell/>
                                                        <Skill>-1</Skill>
                                                        <Type>2</Type>
                                                        <Value>1</Value>
                                                </DiceModifier>
                                        </ListModifiers>
                                        <ResultType>2</ResultType>
                                        <RollType>2</RollType>
                                        <CoachChoices>
                                                <ConcernedTeam>1</ConcernedTeam>
                                                <ListCells/>
                                                <ListDices>(1)</ListDices>
                                                <Reroll>1</Reroll>
                                                <ListSkills/>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
    </ReplayStep>
</Replay>
"""

DODGE_SUCCESS_WITH_SKILL_FIXTURE = """<?xml version="1.0" ?>
<Replay>
    <ReplayStep>
                <RulesEventBoardAction>
                        <PlayerId>37</PlayerId>
                        <RequestType>1</RequestType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <y>12</y>
                                                <x>9</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>13</y>
                                        <x>8</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <RequestType>4</RequestType>
                                        <ListModifiers/>
                                        <ResultType>2</ResultType>
                                        <RollType>2</RollType>
                                        <SubResultType>7</SubResultType>
                                        <CoachChoices>
                                                <ConcernedTeam>1</ConcernedTeam>
                                                <ListCells>
                                                        <Cell>
                                                                <y>13</y>
                                                                <x>8</x>
                                                        </Cell>
                                                </ListCells>
                                                <ListDices>(1)</ListDices>
                                                <ListSkills>
                                                        <SkillInfo>
                                                                <PlayerId>37</PlayerId>
                                                                <SkillId>7</SkillId>
                                                        </SkillInfo>
                                                </ListSkills>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
                <RulesEventBoardAction>
                        <PlayerId>37</PlayerId>
                        <RequestType>1</RequestType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <y>12</y>
                                                <x>9</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>13</y>
                                        <x>8</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <Requirement>4</Requirement>
                                        <RollStatus>4</RollStatus>
                                        <ListModifiers>
                                                <DiceModifier>
                                                        <Cell/>
                                                        <Skill>-1</Skill>
                                                        <Type>2</Type>
                                                        <Value>1</Value>
                                                </DiceModifier>
                                        </ListModifiers>
                                        <IsOrderCompleted>1</IsOrderCompleted>
                                        <RollType>2</RollType>
                                        <CoachChoices>
                                                <ConcernedTeam>1</ConcernedTeam>
                                                <ListCells/>
                                                <ListDices>(5)</ListDices>
                                                <ListSkills>
                                                        <SkillInfo>
                                                                <PlayerId>37</PlayerId>
                                                                <SkillId>7</SkillId>
                                                        </SkillInfo>
                                                        <SkillInfo>
                                                                <PlayerId>37</PlayerId>
                                                                <SkillId>59</SkillId>
                                                        </SkillInfo>
                                                </ListSkills>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
    </ReplayStep>
</Replay>
"""

ONE_DIE_BLOCK_WITH_RR = """<?xml version="1.0" ?>
<Replay>
    <ReplayStep>
                <RulesEventBoardAction>
                        <PlayerId>41</PlayerId>
                        <RequestType>1</RequestType>
                        <ActionType>2</ActionType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <y>10</y>
                                                <x>12</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>11</y>
                                        <x>13</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <RequestType>5</RequestType>
                                        <ListModifiers>
                                                <DiceModifier>
                                                        <Cell>
                                                                <y>9</y>
                                                                <x>13</x>
                                                        </Cell>
                                                        <Skill>-1</Skill>
                                                        <Type>13</Type>
                                                </DiceModifier>
                                        </ListModifiers>
                                        <ResultType>2</ResultType>
                                        <RollType>5</RollType>
                                        <CoachChoices>
                                                <ConcernedTeam>1</ConcernedTeam>
                                                <ListCells/>
                                                <ListDices>(0,0)</ListDices>
                                                <Reroll>1</Reroll>
                                                <ListSkills/>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
                <RulesEventBoardAction>
                        <PlayerId>41</PlayerId>
                        <RequestType>1</RequestType>
                        <ActionType>2</ActionType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <y>10</y>
                                                <x>12</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>11</y>
                                        <x>13</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <RollStatus>1</RollStatus>
                                        <RequestType>2</RequestType>
                                        <ListModifiers>
                                                <DiceModifier>
                                                        <Cell>
                                                                <y>9</y>
                                                                <x>13</x>
                                                        </Cell>
                                                        <Skill>-1</Skill>
                                                        <Type>13</Type>
                                                </DiceModifier>
                                        </ListModifiers>
                                        <ResultType>2</ResultType>
                                        <RollType>5</RollType>
                                        <CoachChoices>
                                                <ConcernedTeam>1</ConcernedTeam>
                                                <ListCells/>
                                                <ListDices>(1,3)</ListDices>
                                                <ListSkills/>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
                <RulesEventBoardAction>
                        <PlayerId>41</PlayerId>
                        <RequestType>1</RequestType>
                        <ActionType>2</ActionType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <y>10</y>
                                                <x>12</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>11</y>
                                        <x>13</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <RollStatus>1</RollStatus>
                                        <ListModifiers>
                                                <DiceModifier>
                                                        <Cell>
                                                                <y>9</y>
                                                                <x>13</x>
                                                        </Cell>
                                                        <Skill>-1</Skill>
                                                        <Type>13</Type>
                                                </DiceModifier>
                                        </ListModifiers>
                                        <IsOrderCompleted>1</IsOrderCompleted>
                                        <RollType>5</RollType>
                                        <CoachChoices>
                                                <ListCells/>
                                                <ListDices>(1,3)</ListDices>
                                                <ListSkills>
                                                        <SkillInfo>
                                                                <PlayerId>41</PlayerId>
                                                                <SkillId>30</SkillId>
                                                        </SkillInfo>
                                                        <SkillInfo>
                                                                <PlayerId>7</PlayerId>
                                                                <SkillId>30</SkillId>
                                                        </SkillInfo>
                                                </ListSkills>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
    </ReplayStep>
</Replay>
"""

ONE_DIE_BLOCK_NO_RR = """<?xml version="1.0" ?>
<Replay>
    <ReplayStep>
                <RulesEventBoardAction>
                        <PlayerId>43</PlayerId>
                        <RequestType>1</RequestType>
                        <ActionType>1</ActionType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <y>7</y>
                                                <x>12</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>7</y>
                                        <x>13</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <RequestType>2</RequestType>
                                        <ListModifiers>
                                                <DiceModifier>
                                                        <Cell>
                                                                <y>8</y>
                                                                <x>12</x>
                                                        </Cell>
                                                        <Skill>-1</Skill>
                                                        <Type>13</Type>
                                                </DiceModifier>
                                        </ListModifiers>
                                        <ResultType>2</ResultType>
                                        <RollType>5</RollType>
                                        <CoachChoices>
                                                <ConcernedTeam>1</ConcernedTeam>
                                                <ListCells/>
                                                <ListDices>(3,6)</ListDices>
                                                <ListSkills/>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
                <RulesEventBoardAction>
                        <PlayerId>43</PlayerId>
                        <RequestType>1</RequestType>
                        <ActionType>1</ActionType>
                        <Order>
                                <CellTo>
                                        <Cell>
                                                <y>7</y>
                                                <x>12</x>
                                        </Cell>
                                </CellTo>
                                <CellFrom>
                                        <y>7</y>
                                        <x>13</x>
                                </CellFrom>
                        </Order>
                        <Results>
                                <BoardActionResult>
                                        <ListModifiers>
                                                <DiceModifier>
                                                        <Cell>
                                                                <y>8</y>
                                                                <x>12</x>
                                                        </Cell>
                                                        <Skill>-1</Skill>
                                                        <Type>13</Type>
                                                </DiceModifier>
                                        </ListModifiers>
                                        <IsOrderCompleted>1</IsOrderCompleted>
                                        <RollType>5</RollType>
                                        <CoachChoices>
                                                <ListCells/>
                                                <ListDices>(3,6)</ListDices>
                                                <ListSkills/>
                                        </CoachChoices>
                                </BoardActionResult>
                        </Results>
                </RulesEventBoardAction>
    </ReplayStep>
</Replay>
"""
